export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#663825 \
  --color=bg:#150b07 \
  --color=border:#d28b61 \
  --color=fg:#ffeedd \
  --color=gutter:#150b07 \
  --color=header:#ff7733 \
  --color=hl+:#ffaa77 \
  --color=hl:#ffaa77 \
  --color=info:#664433 \
  --color=marker:#dd2222 \
  --color=pointer:#dd2222 \
  --color=prompt:#ffaa77 \
  --color=query:#ffeedd:regular \
  --color=scrollbar:#d28b61 \
  --color=separator:#ff7733 \
  --color=spinner:#dd2222 \
"
