export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#664536 \
  --color=bg:#150e0c \
  --color=border:#d0957a \
  --color=fg:#fff4ee \
  --color=gutter:#150e0c \
  --color=header:#fa933a \
  --color=hl+:#fdb594 \
  --color=hl:#fdb594 \
  --color=info:#725248 \
  --color=marker:#ee506a \
  --color=pointer:#ee506a \
  --color=prompt:#fdb594 \
  --color=query:#fff4ee:regular \
  --color=scrollbar:#d0957a \
  --color=separator:#fa933a \
  --color=spinner:#ee506a \
"
