; Tokyo Night Tokyo Night Fire
; Upstream: https://github.com/mrl00/tokyofire.nvim/raw/main/extras/spicetify/tokyonight_fire/color.ini

[fire]
text           = fff4ee
subtext        = dfbdba
main           = 1b1310
sidebar        = 150e0c
player         = 150e0c
card           = 30201b
shadow         = 100a08
main-secondary = 664536
selected-row   = 30201b
button         = fa933a
button-active  = f89068
button-disabled = 725248
nav-active     = fa933a
play-button    = f89068
tab-active     = fa933a
notification   = fa933a
playback-bar   = fa933a
misc           = b08379
