; Tokyo Night Tokyo Night Hell
; Upstream: https://github.com/mrl00/tokyofire.nvim/raw/main/extras/spicetify/tokyonight_hell/color.ini

[hell]
text           = fff0e5
subtext        = eebb99
main           = 1c0f0a
sidebar        = 150b07
player         = 150b07
card           = 331a12
shadow         = 0f0704
main-secondary = 6e3f28
selected-row   = 331a12
button         = ff7733
button-active  = ff7744
button-disabled = 885544
nav-active     = ff7733
play-button    = ff7744
tab-active     = ff7733
notification   = ff7733
playback-bar   = ff7733
misc           = cc7755
