[[Tokyo Night Fire]]
  palette = "#160f0d:#ff6e6c:#f89068:#fede6d:#fceed2:#f56d88:#fdaf8b:#dfbdba:#442821:#ff6e6c:#f89068:#fede6d:#fceed2:#f56d88:#fdaf8b:#f56d88"
  background_color = "#1b1310"
  foreground_color = "#fff4ee"
  