# vim: ft=dosini
#
# aerc TokyoNight styleset
# set styleset-name=tokyonight-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#2c2523
border.bg=#1a1615

title.fg=#151211
title.bg=#fbeee6
title.bold=true

header.fg=#ff9994
#header.bg=#1a1615
header.bold=true

tab.fg=#2c2523
tab.bg=#141110
tab.selected.fg=#151211
tab.selected.bg=#fbeee6

statusline_default.fg=#fbeee6
statusline_default.bg=#141110
statusline_error.fg=#e07070
statusline_success.fg=#f5b041

*error.bold=true
*error.fg=#e07070
*warning.fg=#fde3a7
*success.fg=#f5b041

dirlist_*.bg=#1a1615
dirlist_*.fg=#fbeee6
dirlist_*.selected.bg=#5e4b44
dirlist_*.selected.fg=#fbeee6

msglist_*.bg=#1a1615
msglist_*.fg=#fbeee6
msglist_*.selected.bg=#5e4b44
#msglist_*.selected.fg=#fbeee6
msglist_unread.bold=true
msglist_unread.fg=#fbeee6
msglist_marked.fg=#f5b041
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#2c2523
msglist_pill.bg=#2c2523
msglist_pill.reverse=false

part_*.fg=#fbeee6
part_*.bg=#141110
part_*.selected.fg=#fbeee6
part_*.selected.bg=#2c2523

completion_default.bg=#141110
completion_default.fg=#fbeee6
completion_default.selected.bg=#2c2523
completion_default.selected.fg=#fbeee6
completion_gutter.bg=#2c2523
completion_pill.bg=#2c2523
completion_pill.reverse=false

spinner.bg=#1a1615
spinner.fg=#fbeee6

selector_focused.bold=false
selector_focused.bg=#5e4b44
selector_focused.fg=#fbeee6
selector_chooser.bold=false
selector_chooser.bg=#5e4b44
selector_chooser.fg=#fbeee6
default.selected.bold=false
default.selected.fg=#fbeee6
default.selected.bg=#5e4b44

[viewer]
url.underline=true
url.fg=#8a7a75
header.fg=#ff9ebb
signature.fg=#ff9ebb
diff_add.fg=#453732
diff_del.fg=#4c2d2c
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#fde3a7
quote_2.fg=#f1a98c
quote_3.fg=#f1a98c
quote_3.dim=true
quote_4.fg=#fbeee6
quote_4.dim=true
quote_x.fg=#7f6c68
quote_x.dim=true

