# vim: ft=dosini
#
# aerc TokyoNight styleset
# set styleset-name=tokyonight-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#3e2f2e
border.bg=#1b1310

title.fg=#160f0d
title.bg=#fceed2
title.bold=true

header.fg=#ff6e6c
#header.bg=#1b1310
header.bold=true

tab.fg=#3e2f2e
tab.bg=#150e0c
tab.selected.fg=#160f0d
tab.selected.bg=#fceed2

statusline_default.fg=#fff4ee
statusline_default.bg=#150e0c
statusline_error.fg=#de5152
statusline_success.fg=#fa9c3a

*error.bold=true
*error.fg=#de5152
*warning.fg=#fede6d
*success.fg=#fa9c3a

dirlist_*.bg=#1b1310
dirlist_*.fg=#fff4ee
dirlist_*.selected.bg=#664536
dirlist_*.selected.fg=#fff4ee

msglist_*.bg=#1b1310
msglist_*.fg=#fff4ee
msglist_*.selected.bg=#664536
#msglist_*.selected.fg=#fff4ee
msglist_unread.bold=true
msglist_unread.fg=#fceed2
msglist_marked.fg=#fa933a
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#30201b
msglist_pill.bg=#3e2f2e
msglist_pill.reverse=false

part_*.fg=#fff4ee
part_*.bg=#150e0c
part_*.selected.fg=#fff4ee
part_*.selected.bg=#3e2f2e

completion_default.bg=#150e0c
completion_default.fg=#fff4ee
completion_default.selected.bg=#3e2f2e
completion_default.selected.fg=#fff4ee
completion_gutter.bg=#30201b
completion_pill.bg=#3e2f2e
completion_pill.reverse=false

spinner.bg=#1b1310
spinner.fg=#fff4ee

selector_focused.bold=false
selector_focused.bg=#664536
selector_focused.fg=#fff4ee
selector_chooser.bold=false
selector_chooser.bg=#664536
selector_chooser.fg=#fff4ee
default.selected.bold=false
default.selected.fg=#fff4ee
default.selected.bg=#664536

[viewer]
url.underline=true
url.fg=#a38176
header.fg=#f56d88
signature.fg=#f56d88
diff_add.fg=#4a3328
diff_del.fg=#4c2321
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#fede6d
quote_2.fg=#f89068
quote_3.fg=#f89068
quote_3.dim=true
quote_4.fg=#fceed2
quote_4.dim=true
quote_x.fg=#b08379
quote_x.dim=true

