# vim: ft=dosini
#
# aerc TokyoNight styleset
# set styleset-name=tokyonight-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#331a12
border.bg=#1c0f0a

title.fg=#160c08
title.bg=#ffeedd
title.bold=true

header.fg=#ff4444
#header.bg=#1c0f0a
header.bold=true

tab.fg=#331a12
tab.bg=#150b07
tab.selected.fg=#160c08
tab.selected.bg=#ffeedd

statusline_default.fg=#ffeedd
statusline_default.bg=#150b07
statusline_error.fg=#dd3333
statusline_success.fg=#ff8833

*error.bold=true
*error.fg=#dd3333
*warning.fg=#ffbb33
*success.fg=#ff8833

dirlist_*.bg=#1c0f0a
dirlist_*.fg=#ffeedd
dirlist_*.selected.bg=#663825
dirlist_*.selected.fg=#ffeedd

msglist_*.bg=#1c0f0a
msglist_*.fg=#ffeedd
msglist_*.selected.bg=#663825
#msglist_*.selected.fg=#ffeedd
msglist_unread.bold=true
msglist_unread.fg=#ffeedd
msglist_marked.fg=#ff7733
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#331a12
msglist_pill.bg=#331a12
msglist_pill.reverse=false

part_*.fg=#ffeedd
part_*.bg=#150b07
part_*.selected.fg=#ffeedd
part_*.selected.bg=#331a12

completion_default.bg=#150b07
completion_default.fg=#ffeedd
completion_default.selected.bg=#331a12
completion_default.selected.fg=#ffeedd
completion_gutter.bg=#331a12
completion_pill.bg=#331a12
completion_pill.reverse=false

spinner.bg=#1c0f0a
spinner.fg=#ffeedd

selector_focused.bold=false
selector_focused.bg=#663825
selector_focused.fg=#ffeedd
selector_chooser.bold=false
selector_chooser.bg=#663825
selector_chooser.fg=#ffeedd
default.selected.bold=false
default.selected.fg=#ffeedd
default.selected.bg=#663825

[viewer]
url.underline=true
url.fg=#997766
header.fg=#ff5588
signature.fg=#ff5588
diff_add.fg=#4a291b
diff_del.fg=#4c1814
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#ffbb33
quote_2.fg=#ff7744
quote_3.fg=#ff7744
quote_3.dim=true
quote_4.fg=#ffeedd
quote_4.dim=true
quote_x.fg=#996655
quote_x.dim=true

