[colors]
foreground = "#fff4ee"
background = "#1b1310"
cursor_bg = "#fff4ee"
cursor_border = "#fff4ee"
cursor_fg = "#1b1310"
selection_bg = "#664536"
selection_fg = "#fff4ee"
split = "#fceed2"
compose_cursor = "#fa933a"
scrollbar_thumb = "#30201b"

ansi = ["#160f0d", "#ff6e6c", "#f89068", "#fede6d", "#fceed2", "#f56d88", "#fdaf8b", "#dfbdba"]
brights = ["#442821", "#ff8685", "#ffa181", "#ffedbd", "#fffdfb", "#ff7f97", "#ffc1a8", "#fff4ee"]

[colors.tab_bar]
inactive_tab_edge = "#150e0c"
background = "#1b1310"

[colors.tab_bar.active_tab]
fg_color = "#150e0c"
bg_color = "#fceed2"

[colors.tab_bar.inactive_tab]
fg_color = "#725248"
bg_color = "#30201b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#fceed2"
bg_color = "#30201b"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#fceed2"
bg_color = "#1b1310"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#fceed2"
bg_color = "#1b1310"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_fire"