[colors]
foreground = "#fff0e5"
background = "#1c0f0a"
cursor_bg = "#fff0e5"
cursor_border = "#fff0e5"
cursor_fg = "#1c0f0a"
selection_bg = "#6e3f28"
selection_fg = "#fff0e5"
split = "#ffeedd"
compose_cursor = "#ff7733"
scrollbar_thumb = "#331a12"

ansi = ["#160c08", "#ff4444", "#ff7744", "#ffbb33", "#ffeedd", "#ee3333", "#ff9966", "#eebb99"]
brights = ["#4a2218", "#ff6565", "#ff8e6e", "#ffcc87", "#ffffff", "#ff4343", "#ffad8b", "#fff0e5"]

[colors.tab_bar]
inactive_tab_edge = "#150b07"
background = "#1c0f0a"

[colors.tab_bar.active_tab]
fg_color = "#150b07"
bg_color = "#ffeedd"

[colors.tab_bar.inactive_tab]
fg_color = "#885544"
bg_color = "#331a12"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#ffeedd"
bg_color = "#331a12"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#ffeedd"
bg_color = "#1c0f0a"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ffeedd"
bg_color = "#1c0f0a"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_hellfire"