# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night White Fire
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_whitefire.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1615'
foreground = '#fff8f5'

# Normal colors
[colors.normal]
black = '#151211'
red = '#ff9994'
green = '#f1a98c'
yellow = '#fde3a7'
blue = '#fbeee6'
magenta = '#ff9ebb'
cyan = '#fbc5b0'
white = '#d0c0ba'

# Bright colors
[colors.bright]
black = '#3d2e2a'
red = '#ffaeaa'
green = '#fdb89d'
yellow = '#fff3da'
blue = '#fffffe'
magenta = '#ffb3c9'
cyan = '#ffd6c8'
white = '#fff8f5'
