# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Fire
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_fire.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1b1310'
foreground = '#fff4ee'

# Normal colors
[colors.normal]
black = '#160f0d'
red = '#ff6e6c'
green = '#f89068'
yellow = '#fede6d'
blue = '#fceed2'
magenta = '#f56d88'
cyan = '#fdaf8b'
white = '#dfbdba'

# Bright colors
[colors.bright]
black = '#442821'
red = '#ff8685'
green = '#ffa181'
yellow = '#ffedbd'
blue = '#fffdfb'
magenta = '#ff7f97'
cyan = '#ffc1a8'
white = '#fff4ee'
