[[themes]]
name = "Tokyo Night Hell Fire"
[themes.palette]
background = "#150b07"
foreground = "#eebb99"
black = "#4a2218"
red = "#ff4444"
green = "#ff7744"
yellow = "#ffbb33"
blue = "#ffeedd"
magenta = "#ee3333"
cyan = "#ff9966"
white = "#eebb99"
bright_black = "#1c0f0a"
bright_red = "#dd3333"
bright_green = "#ff8833"
bright_yellow = "#ff7733"
bright_blue = "#ffaa77"
bright_magenta = "#dd2222"
bright_cyan = "#ffcc44"
bright_white = "#fff0e5"
