[[themes]]
name = "Tokyo Night Fire"
[themes.palette]
background = "#150e0c"
foreground = "#dfbdba"
black = "#442821"
red = "#ff6e6c"
green = "#f89068"
yellow = "#fede6d"
blue = "#fceed2"
magenta = "#f56d88"
cyan = "#fdaf8b"
white = "#dfbdba"
bright_black = "#1b1310"
bright_red = "#de5152"
bright_green = "#fa9c3a"
bright_yellow = "#fa933a"
bright_blue = "#fdb594"
bright_magenta = "#ee506a"
bright_cyan = "#fed576"
bright_white = "#fff4ee"
