[[themes]]
name = "Tokyo Night Fire"
[themes.palette]
background = "#141110"
foreground = "#a08a85"
black = "#3d2e2a"
red = "#ff9994"
green = "#f1a98c"
yellow = "#fde3a7"
blue = "#fbeee6"
magenta = "#ff9ebb"
cyan = "#fbc5b0"
white = "#a08a85"
bright_black = "#1a1615"
bright_red = "#e07070"
bright_green = "#f5b041"
bright_yellow = "#f5b041"
bright_blue = "#fbc5b0"
bright_magenta = "#ff7eb3"
bright_cyan = "#fde3a7"
bright_white = "#fbeee6"
