---@type Palette
return {
  bg = "#c5c4c4",
  bg_dark = "#c4c3c3",
  bg_dark1 = "#c3c2c2",
  bg_highlight = "#cac8c8",
  blue = "#fefaf8",
  blue0 = "#f0e5e1",
  blue1 = "#fef0eb",
  blue2 = "#fcebcf",
  blue5 = "#fef8e9",
  blue6 = "#ffe6ee",
  blue7 = "#cecac9",
  comment = "#dfdad9",
  cyan = "#fef0eb",
  dark3 = "#d6d3d2",
  dark5 = "#e1dddc",
  fg = "#fefaf8",
  fg_dark = "#e7e1e0",
  fg_gutter = "#cac8c8",
  green = "#fbe9e2",
  green1 = "#fcebcf",
  green2 = "#f0e5e1",
  magenta = "#ffe6ee",
  magenta2 = "#ffdeec",
  orange = "#fcebcf",
  purple = "#ffe6ee",
  red = "#ffe5e4",
  red1 = "#f7dbdb",
  teal = "#fbe9e2",
  terminal_black = "#cecac9",
  yellow = "#fef8e9",
  git = {
    add = "#fbe9e2",
    change = "#fcebcf",
    delete = "#ffe5e4",
  },
}
