attribute = { fg = "#fdaf8b" }
comment = { fg = "#b08379", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#fede6d" }
constant = { fg = "#fa933a" }
"constant.builtin" = { fg = "#fdb594" }
"constant.builtin.boolean" = { fg = "#fa933a" }
"constant.character" = { fg = "#f89068" }
"constant.character.escape" = { fg = "#f56d88" }
"constant.numeric" = { fg = "#fa933a" }
"constant.numeric.float" = { fg = "#fa933a" }
"constant.numeric.integer" = { fg = "#fa933a" }
constructor = { fg = "#fdb594" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#211613", fg = "#fa9c3a" }
"diff.delta.moved" = { fg = "#fceed2" }
"diff.minus" = { bg = "#4c2321", fg = "#ff6e6c" }
"diff.plus" = { bg = "#4a3328", fg = "#f89068" }
error = { fg = "#de5152" }
function = { fg = "#fceed2" }
"function.builtin" = { fg = "#fdb594" }
"function.macro" = { fg = "#fdaf8b" }
"function.method" = { fg = "#fceed2" }
"function.special" = { fg = "#fdaf8b" }
hint = { fg = "#f89068" }
info = { fg = "#fa9c3a" }
keyword = { fg = "#f56d88", modifiers = ["italic"] }
"keyword.control" = { fg = "#f56d88" }
"keyword.control.conditional" = { fg = "#f56d88" }
"keyword.control.exception" = { fg = "#f56d88" }
"keyword.control.repeat" = { fg = "#f56d88" }
"keyword.control.return" = { fg = "#f56d88", modifiers = ["italic"] }
"keyword.directive" = { fg = "#fdaf8b" }
"keyword.function" = { fg = "#f56d88" }
"keyword.operator" = { fg = "#f56d88" }
label = { fg = "#fceed2" }
"markup.bold" = { fg = "#fff4ee", modifiers = ["bold"] }
"markup.heading" = { fg = "#fceed2", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#150e0c", fg = "#fff4ee" }
"markup.heading.hover" = { bg = "#372928" }
"markup.italic" = { fg = "#fff4ee", modifiers = ["italic"] }
"markup.link" = { fg = "#f89068" }
"markup.link.label" = { fg = "#fdb594" }
"markup.link.text" = { fg = "#f89068" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#fed576" }
"markup.normal.completion" = { fg = "#b08379" }
"markup.normal.hover" = { fg = "#dfbdba" }
"markup.raw" = { fg = "#f89068" }
"markup.raw.inline" = { bg = "#442821", fg = "#fceed2" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#fdaf8b" }
operator = { fg = "#fed576" }
special = { fg = "#fdb594" }
string = { fg = "#f89068" }
"string.regexp" = { fg = "#f57080" }
"string.special" = { fg = "#fdb594" }
tag = { fg = "#f56d88" }
type = { fg = "#fdb594" }
"type.builtin" = { fg = "#d0957a" }
"type.enum" = { fg = "#fdb594" }
"type.enum.variant" = { fg = "#fa933a" }
"ui.background" = { bg = "bg" }
"ui.bufferline.active" = { bg = "bg_visual", fg = "fg" }
"ui.cursor" = { bg = "#fff4ee", fg = "#1b1310" }
"ui.cursor.match" = { fg = "#fa933a", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3e2f2e" }
"ui.linenr.select" = { fg = "#fa933a", modifiers = ["bold"] }
"ui.menu" = { bg = "#150e0c", fg = "#fff4ee" }
"ui.menu.scroll" = { bg = 2169367, fg = 4075310 }
"ui.menu.selected" = { bg = "#372928" }
"ui.popup" = { bg = "#150e0c", fg = "#d0957a" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#150e0c", fg = "#dfbdba" }
"ui.statusline.inactive" = { bg = "#150e0c", fg = "#3e2f2e" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#1b1310", fg = "#fff4ee" }
"ui.text.focus" = { bg = "#664536" }
"ui.text.inactive" = { fg = "#b08379", modifiers = ["italic"] }
"ui.text.info" = { bg = "#150e0c", fg = "#fff4ee" }
"ui.virtual.inlay-hint" = { bg = "#312019", fg = "#f89068" }
"ui.window" = { fg = "#160f0d", modifiers = ["bold"] }
variable = { fg = "#fff4ee" }
"variable.builtin" = { fg = "#ff6e6c" }
"variable.other.member" = { fg = "#fa9c3a" }
"variable.parameter" = { fg = "#fede6d" }
warning = { fg = "#fede6d" }

[palette]
bg = "#1b1310"
bg_dark = "#150e0c"
bg_dark1 = "#100a08"
bg_float = "#150e0c"
bg_highlight = "#30201b"
bg_popup = "#150e0c"
bg_search = "#d69170"
bg_sidebar = "#150e0c"
bg_statusline = "#150e0c"
bg_visual = "#664536"
black = "#160f0d"
blue = "#fceed2"
blue0 = "#d69170"
blue1 = "#fdb594"
blue2 = "#fa9c3a"
blue5 = "#fed576"
blue6 = "#f57080"
blue7 = "#442821"
border = "#160f0d"
border_highlight = "#d0957a"
comment = "#b08379"
cyan = "#fdaf8b"
dark3 = "#725248"
dark5 = "#a38176"
"diff.add" = "#4a3328"
"diff.change" = "#211613"
"diff.delete" = "#4c2321"
"diff.text" = "#442821"
error = "#de5152"
fg = "#fff4ee"
fg_dark = "#dfbdba"
fg_float = "#fff4ee"
fg_gutter = "#3e2f2e"
fg_sidebar = "#dfbdba"
"git.add" = "#f89068"
"git.change" = "#fa9c3a"
"git.delete" = "#ff6e6c"
"git.ignore" = "#725248"
green = "#f89068"
green1 = "#fa9c3a"
green2 = "#d69170"
hint = "#f89068"
info = "#fa9c3a"
magenta = "#f56d88"
magenta2 = "#ee506a"
orange = "#fa933a"
purple = "#f56d88"
rainbow = "#fceed2"
"rainbow.2" = "#fede6d"
"rainbow.3" = "#f89068"
"rainbow.4" = "#f89068"
"rainbow.5" = "#f56d88"
"rainbow.6" = "#f56d88"
"rainbow.7" = "#fa933a"
"rainbow.8" = "#ff6e6c"
red = "#ff6e6c"
red1 = "#de5152"
teal = "#f89068"
"terminal.black" = "#160f0d"
"terminal.black_bright" = "#442821"
"terminal.blue" = "#fceed2"
"terminal.blue_bright" = "#fffdfb"
"terminal.cyan" = "#fdaf8b"
"terminal.cyan_bright" = "#ffc1a8"
"terminal.green" = "#f89068"
"terminal.green_bright" = "#ffa181"
"terminal.magenta" = "#f56d88"
"terminal.magenta_bright" = "#ff7f97"
"terminal.red" = "#ff6e6c"
"terminal.red_bright" = "#ff8685"
"terminal.white" = "#dfbdba"
"terminal.white_bright" = "#fff4ee"
"terminal.yellow" = "#fede6d"
"terminal.yellow_bright" = "#ffedbd"
terminal_black = "#442821"
todo = "#fceed2"
warning = "#fede6d"
yellow = "#fede6d"