[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#dfbdba", italic = true }

# Hovered
hovered         = { bg = "#30201b" }
preview_hovered = { bg = "#30201b" }

# Find
find_keyword  = { fg = "#150e0c", bg = "#fa933a", bold = true }
find_position = { fg = "#fa9c3a", bg = "#312114", bold = true }

# Marker
marker_copied   = { fg = "#f89068", bg = "#f89068" }
marker_cut      = { fg = "#ff6e6c", bg = "#ff6e6c" }
marker_marked   = { fg = "#f56d88", bg = "#f56d88" }
marker_selected = { fg = "#fceed2", bg = "#fceed2" }

# Count
count_copied   = { fg = "#150e0c", bg = "#f89068" }
count_cut      = { fg = "#150e0c", bg = "#ff6e6c" }
count_selected = { fg = "#150e0c", bg = "#fceed2" }

# Border
border_symbol = "│"
border_style  = { fg = "#d0957a" }

# Tab
[tabs]
active   = { fg = "#160f0d", bg = "#fceed2" }
inactive = { fg = "#fceed2", bg = "#3e2f2e" }

[mode]
normal_main = { fg = "#160f0d", bg = "#fceed2", bold = true }
normal_alt  = { fg = "#fceed2", bg = "#3e2f2e" }

select_main = { fg = "#160f0d", bg = "#f56d88", bold = true }
select_alt  = { fg = "#f56d88", bg = "#3e2f2e" }

unset_main  = { fg = "#160f0d", bg = "#f56d88", bold = true }
unset_alt   = { fg = "#f56d88", bg = "#3e2f2e" }

[status]
overall   = { fg = "#fff4ee", bg = "#150e0c" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#fff4ee", bold = true }
progress_normal = { fg = "#d69170", bg = "#30201b" }
progress_error  = { fg = "#de5152", bg = "#30201b" }

# Permissions
perm_type  = { fg = "#fceed2" }
perm_read  = { fg = "#fede6d" }
perm_write = { fg = "#ff6e6c" }
perm_exec  = { fg = "#f89068" }
perm_sep   = { fg = "#442821" }

[pick]
border   = { fg = "#d0957a" }
active   = { fg = "#fff4ee",  bg = "#664536" }
inactive = { fg = "#fff4ee" }

# Input
[input]
border   = { fg = "#fa9c3a" }
title    = { fg = "#fa9c3a" }
value    = { fg = "#f56d88" }
selected = { bg = "#664536" }

# Completion
[cmp]
border   = { fg = "#fa9c3a" }
active   = { fg = "#fff4ee", bg = "#372928" }
inactive = { fg = "#fff4ee" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#d0957a" }
title   = { fg = "#d0957a" }
hovered = { fg = "#fff4ee", bg = "#664536" }

# Which
[which]
cols            = 3
mask            = { bg = "#150e0c" }
cand            = { fg = "#fdaf8b" }
rest            = { fg = "#fceed2" }
desc            = { fg = "#f56d88" }
separator       = " ➜ "
separator_style = { fg = "#b08379" }

# Confirm
[confirm]
border  = { fg = "#fa9c3a" }
title   = { fg = "#d0957a" }
content = {}
list    = {}
btn_yes = { bg = "#664536" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#d0957a" }
title   = { fg = "#d0957a" }

# Notify
[notify]
title_info  = { fg = "#fa9c3a" }
title_warn  = { fg = "#fede6d" }
title_error = { fg = "#de5152" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#f89068" }
run     = { fg = "#f56d88" }
desc    = { fg = "#fdaf8b" }
hovered = { bg = "#30201b" }
footer  = { fg = "#fff4ee", bg = "#1b1310" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#fede6d" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f56d88" },

	# Archives
	{ mime = "application/*zip", fg = "#ff6e6c" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff6e6c" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#fdaf8b" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ff6e6c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff6e6c" },
	{ name = "*", is = "exec"  , fg = "#f89068" },

	# Fallback
	{ name = "*/", fg = "#fceed2" },
	{ name = "*", fg = "#fff4ee" }
]
    