; Tokyo Night Tokyo Night White Fire
; Upstream: https://github.com/mrl00/tokyofire.nvim/raw/main/extras/spicetify/tokyonight_whitefire/color.ini

[whitefire]
text           = fff8f5
subtext        = d0c0ba
main           = 1a1615
sidebar        = 141110
player         = 141110
card           = 2c2523
shadow         = 100d0c
main-secondary = 5e4b44
selected-row   = 2c2523
button         = f5b041
button-active  = f1a98c
button-disabled = 5c4f4b
nav-active     = f5b041
play-button    = f1a98c
tab-active     = f5b041
notification   = f5b041
playback-bar   = f5b041
misc           = a0908a
