# vim:ft=kitty

## name: Tokyo Night Hell Fire
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_hellfire.conf


background #1c0f0a
foreground #fff0e5
selection_background #6e3f28
selection_foreground #fff0e5
url_color #ff8833
cursor #fff0e5
cursor_text_color #1c0f0a

# Tabs
active_tab_background #ffeedd
active_tab_foreground #150b07
inactive_tab_background #331a12
inactive_tab_foreground #885544
#tab_bar_background #160c08

# Windows
active_border_color #ffeedd
inactive_border_color #331a12

# normal
color0 #160c08
color1 #ff4444
color2 #ff7744
color3 #ffbb33
color4 #ffeedd
color5 #ee3333
color6 #ff9966
color7 #eebb99

# bright
color8  #4a2218
color9  #ff6565
color10 #ff8e6e
color11 #ffcc87
color12 #ffffff
color13 #ff4343
color14 #ffad8b
color15 #fff0e5

# extended colors
color16 #ff7733
color17 #dd3333
