# vim:ft=kitty

## name: Tokyo Night Fire
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_fire.conf


background #1b1310
foreground #fff4ee
selection_background #664536
selection_foreground #fff4ee
url_color #fa9c3a
cursor #fff4ee
cursor_text_color #1b1310

# Tabs
active_tab_background #fceed2
active_tab_foreground #150e0c
inactive_tab_background #30201b
inactive_tab_foreground #725248
#tab_bar_background #160f0d

# Windows
active_border_color #fceed2
inactive_border_color #30201b

# normal
color0 #160f0d
color1 #ff6e6c
color2 #f89068
color3 #fede6d
color4 #fceed2
color5 #f56d88
color6 #fdaf8b
color7 #dfbdba

# bright
color8  #442821
color9  #ff8685
color10 #ffa181
color11 #ffedbd
color12 #fffdfb
color13 #ff7f97
color14 #ffc1a8
color15 #fff4ee

# extended colors
color16 #fa933a
color17 #de5152
