# vim:ft=kitty

## name: Tokyo Night Fire
## license: MIT
## author: Folke Lemaitre
## upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty/tokyonight_fire.conf


background #1a1615
foreground #fbeee6
selection_background #5e4b44
selection_foreground #fbeee6
url_color #f5b041
cursor #fbeee6
cursor_text_color #1a1615

# Tabs
active_tab_background #fbeee6
active_tab_foreground #141110
inactive_tab_background #2c2523
inactive_tab_foreground #5c4f4b
#tab_bar_background #151211

# Windows
active_border_color #fbeee6
inactive_border_color #2c2523

# normal
color0 #151211
color1 #ff9994
color2 #f1a98c
color3 #fde3a7
color4 #fbeee6
color5 #ff9ebb
color6 #fbc5b0
color7 #a08a85

# bright
color8  #3d2e2a
color9  #ffaeaa
color10 #fdb89d
color11 #fff3da
color12 #fffffe
color13 #ffb3c9
color14 #ffd6c8
color15 #fbeee6

# extended colors
color16 #f5b041
color17 #e07070
