name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
      - uses: leafo/gh-actions-luarocks@v4
      - run: luarocks install luassert
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: ./scripts/test
