name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  test:
    runs-on: ubuntu-latest
    env:
      LUA_PATH: "/home/runner/.luarocks/share/lua/5.1/?.lua;/home/runner/.luarocks/share/lua/5.1/?/init.lua;;"
      LUA_CPATH: "/home/runner/.luarocks/lib/lua/5.1/?.so;;"
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: sudo apt-get update && sudo apt-get install -y luarocks
      - run: luarocks install --local luassert
      - run: ./scripts/test
