# -----------------------------------------------------------------------------
# Theme: Tokyo Night Fire
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/termux/tokyonight_fire.properties
# -----------------------------------------------------------------------------

background: #1a1615
foreground: #fbeee6

# Normal colors
color0:  #151211
color1:  #ff9994
color2:  #f1a98c
color3:  #fde3a7
color4:  #fbeee6
color5:  #ff9ebb
color6:  #fbc5b0
color7:  #a08a85

# Bright colors
color8:  #3d2e2a
color9:  #ffaeaa
color10: #fdb89d
color11: #fff3da
color12: #fffffe
color13: #ffb3c9
color14: #ffd6c8
color15: #fbeee6

# Extended colors
color16: #f5b041
color17: #e07070
