# -----------------------------------------------------------------------------
# Theme: Tokyo Night Hell Fire
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/termux/tokyonight_hellfire.properties
# -----------------------------------------------------------------------------

background: #1c0f0a
foreground: #ffeedd

# Normal colors
color0:  #160c08
color1:  #ff4444
color2:  #ff7744
color3:  #ffbb33
color4:  #ffeedd
color5:  #ff5588
color6:  #ff9966
color7:  #cc9988

# Bright colors
color8:  #4a2218
color9:  #ff6565
color10: #ff8e6e
color11: #ffcc87
color12: #ffffff
color13: #ff7297
color14: #ffad8b
color15: #ffeedd

# Extended colors
color16: #ff7733
color17: #dd3333
