# -----------------------------------------------------------------------------
# Theme: Tokyo Night Fire
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/termux/tokyonight_fire.properties
# -----------------------------------------------------------------------------

background: #1b1310
foreground: #fff4ee

# Normal colors
color0:  #160f0d
color1:  #ff6e6c
color2:  #f89068
color3:  #fede6d
color4:  #fceed2
color5:  #f56d88
color6:  #fdaf8b
color7:  #dfbdba

# Bright colors
color8:  #442821
color9:  #ff8685
color10: #ffa181
color11: #ffedbd
color12: #fffdfb
color13: #ff7f97
color14: #ffc1a8
color15: #fff4ee

# Extended colors
color16: #fa933a
color17: #de5152
